// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';
export const BASE_URL = 'BASE_URL';
export const SET_BUTTON_VARIANT = 'SET_BUTTON_VARIANT';
export const SET_DEBITUR_DATA = 'SET_DEBITUR_DATA';
export const GET_DEBITUR_DATA = 'GET_DEBITUR_DATA';